# Generated by Django 4.2.5 on 2023-10-17 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_problem_topic_solution_room_problem_topic_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='study_mate',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
