# Generated by Django 4.2.6 on 2023-10-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='asked_by',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='room',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='room',
            name='members',
        ),
        migrations.RemoveField(
            model_name='room',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='answered_by',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='problem',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
