# Generated by Django 4.2.5 on 2023-11-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('main', '0009_remove_userprofile_is_superuser_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='topic_followed',
            field=models.ManyToManyField(blank=True, to='rooms.topic'),
        ),
    ]
